force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Ambitos__c.field-meta.xml
<CustomField>
    <fullName>Ambitos__c</fullName>
    <label>Ámbitos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ambitos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/code_bdns__c.field-meta.xml
<CustomField>
    <fullName>code_bdns__c</fullName>
    <label>Code bdns</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CodigoImpactoGenero__c.field-meta.xml
<CustomField>
    <fullName>CodigoImpactoGenero__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>9000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/DescripcionOtro__c.field-meta.xml
<CustomField>
    <fullName>DescripcionOtro__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Entidades__c.field-meta.xml
<CustomField>
    <fullName>Entidades__c</fullName>
    <label>Entidad 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/ExtractoCastellano__c.field-meta.xml
<CustomField>
    <fullName>ExtractoCastellano__c</fullName>
    <label>Extracto castellano</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/ExtractoOtraLengua__c.field-meta.xml
<CustomField>
    <fullName>ExtractoOtraLengua__c</fullName>
    <label>Extracto otra lengua</label>
    <length>7500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_envio_Convocatoria__c.field-meta.xml
<CustomField>
    <fullName>Fecha_envio_Convocatoria__c</fullName>
    <label>Fecha envío</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/fecha_modificacion__c.field-meta.xml
<CustomField>
    <fullName>fecha_modificacion__c</fullName>
    <label>Fecha modificación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_publicacion_Convocatoria__c.field-meta.xml
<CustomField>
    <fullName>Fecha_publicacion_Convocatoria__c</fullName>
    <label>Fecha publicación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/FechaFinSolicitud__c.field-meta.xml
<CustomField>
    <fullName>FechaFinSolicitud__c</fullName>
    <label>Fecha Fin Solicitud</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/FechaJustificacion__c.field-meta.xml
<CustomField>
    <fullName>FechaJustificacion__c</fullName>
    <label>Fecha justificación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/fondo_ue__c.field-meta.xml
<CustomField>
    <fullName>fondo_ue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fondo Union Europea</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Id_extracto_diario_oficial_Convocatoria__c.field-meta.xml
<CustomField>
    <fullName>Id_extracto_diario_oficial_Convocatoria__c</fullName>
    <label>Id extracto diario oficial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Importe_total__c.field-meta.xml
<CustomField>
    <fullName>Importe_total__c</fullName>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/InicioSolicitud__c.field-meta.xml
<CustomField>
    <fullName>InicioSolicitud__c</fullName>
    <label>Inicio solicitud</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/NombreDocumentoCastellano__c.field-meta.xml
<CustomField>
    <fullName>NombreDocumentoCastellano__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/NombreDocumentoOtraLengua__c.field-meta.xml
<CustomField>
    <fullName>NombreDocumentoOtraLengua__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/NombreImpactoGenero__c.field-meta.xml
<CustomField>
    <fullName>NombreImpactoGenero__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/NombreJustificacion__c.field-meta.xml
<CustomField>
    <fullName>NombreJustificacion__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/NombreOtrosDocumentos__c.field-meta.xml
<CustomField>
    <fullName>NombreOtrosDocumentos__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/TituloExtractoCastellano__c.field-meta.xml
<CustomField>
    <fullName>TituloExtractoCastellano__c</fullName>
    <label>Título</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/TituloExtractoOtraLengua__c.field-meta.xml
<CustomField>
    <fullName>TituloExtractoOtraLengua__c</fullName>
    <label>Título</label>
    <length>450</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/URL_documentacion_convocatoria__c.field-meta.xml
<CustomField>
    <fullName>URL_documentacion_convocatoria__c</fullName>
    <label>URL documentación convocatoria</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/URL_publicacion_Convocatoria__c.field-meta.xml
<CustomField>
    <fullName>URL_publicacion_Convocatoria__c</fullName>
    <label>URL publicación</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/URLengBR__c.field-meta.xml
<CustomField>
    <fullName>URLengBR__c</fullName>
    <label>URLengBR</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/URLEspBR__c.field-meta.xml
<CustomField>
    <fullName>URLEspBR__c</fullName>
    <label>URLEspBR</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Convocatoria.recordType-meta.xml
<RecordType>
    <fullName>Convocatoria</fullName>
    <active>true</active>
    <label>Convocatoria</label>
</RecordType>

force-app/main/default/globalValueSets/Ambitos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cultura y Deportes</fullName>
    </customValue>
    <customValue>
        <fullName>Infraestructuras (Vías y Obras)</fullName>
    </customValue>
    <customValue>
        <fullName>Medio Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Intervención</fullName>
    </customValue>
    <customValue>
        <fullName>Recaudación</fullName>
    </customValue>
    <customValue>
        <fullName>Benestar</fullName>
    </customValue>
    <customValue>
        <fullName>Turismo</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH (Ofertas de empleo)</fullName>
    </customValue>
    <customValue>
        <fullName>Transparencia</fullName>
    </customValue>
    <customValue>
        <fullName>Asesoría Jurídica (legal)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratación</fullName>
    </customValue>
    <customValue>
        <fullName>Tramitación electrónica</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperación</fullName>
    </customValue>
    <customValue>
        <fullName>Asuntos Sociales (Benestar)</fullName>
        <isActive>false</isActive>
        <label>Asuntos Sociales (Benestar)</label>
    </customValue>
    <customValue>
        <fullName>Intervención y Recaudación</fullName>
        <isActive>false</isActive>
        <label>Intervención y Recaudación</label>
    </customValue>
    <masterLabel>Ámbitos</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Deputación</fullName>
        <default>true</default>
        <label>Deputación Provincial de Ourense</label>
    </customValue>
    <customValue>
        <fullName>Provincia</fullName>
    </customValue>
    <customValue>
        <fullName>Allariz</fullName>
    </customValue>
    <customValue>
        <fullName>Amoeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Arnoia A</fullName>
    </customValue>
    <customValue>
        <fullName>Avión</fullName>
    </customValue>
    <customValue>
        <fullName>Baltar</fullName>
    </customValue>
    <customValue>
        <fullName>Bande</fullName>
    </customValue>
    <customValue>
        <fullName>Baños de Molgas</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadás</fullName>
    </customValue>
    <customValue>
        <fullName>Barco de Valdeorras O</fullName>
    </customValue>
    <customValue>
        <fullName>Beade</fullName>
    </customValue>
    <customValue>
        <fullName>Beariz</fullName>
    </customValue>
    <customValue>
        <fullName>Blancos Os</fullName>
    </customValue>
    <customValue>
        <fullName>Boborás</fullName>
    </customValue>
    <customValue>
        <fullName>Bola A</fullName>
    </customValue>
    <customValue>
        <fullName>Bolo O</fullName>
    </customValue>
    <customValue>
        <fullName>Calvos de Randín</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Avia</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Valdeorras</fullName>
    </customValue>
    <customValue>
        <fullName>Carballiño O</fullName>
    </customValue>
    <customValue>
        <fullName>Cartelle</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo de Miño</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo do Val</fullName>
    </customValue>
    <customValue>
        <fullName>Castro Caldelas</fullName>
    </customValue>
    <customValue>
        <fullName>Celanova</fullName>
    </customValue>
    <customValue>
        <fullName>Cenlle</fullName>
    </customValue>
    <customValue>
        <fullName>Chandrexa de Queixa</fullName>
    </customValue>
    <customValue>
        <fullName>Coles</fullName>
    </customValue>
    <customValue>
        <fullName>Cortegada</fullName>
    </customValue>
    <masterLabel>Entidades</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConvocatoriaService.cls
public class ConvocatoriaService {
    public static void procesarConvocatoria(List<String> detallesJson) {
        for (String jsonDetalle : detallesJson){
            try {
                //Declaracion de variables
                Knowledge__kav knowCastellano = new Knowledge__kav();
                Knowledge__kav knowOtraLengua = new Knowledge__kav();
                List<Knowledge__kav> lstKnowledge = new List<Knowledge__kav>();
                String code_bdns;
                String descripcion;
                Decimal importe_total;
                Boolean fondo_ue;
                Boolean activo;
                String documentoCastellanoNombre;
                String documentoOtraLenguaNombre;
                String uRLEspBR;
                String uRLengBR;
                String solicitudInicioSolicitud;
                Date solicitudFechaFinSolicitud;
                String justificacionNombre;
                Date fechaJustificacion;
                String impactoGeneroCodigo;
                String impactoGeneroNombre;
                String extractoCastellanoTituloExtracto;
                String textoExtractoCastellano;
                String extractoOtraLenguaTituloExtracto;
                String textoExtractoOtraLengua;
                String otroDocDescripcionOtro;
                String otroDocNombre;
                String fecha_modificacion;
                Date publicacionFechaPublicacion;
                String publicacionIdExtractoDiarioOficial;
                String publicacionUrlPublicacion;
                Date fechaEnvio;
                
                
                // Deserializa el JSON en un objeto de Convocatoria
                Convocatoria convocatoria = (Convocatoria) JSON.deserialize(jsonDetalle, Convocatoria.class);
                // Procesar los datos principales de la convocatoria
                if (convocatoria != null) {
                    code_bdns = convocatoria.code_bdns;
                    descripcion = convocatoria.descripcion;
                    importe_total = convocatoria.importe_total;
                    fondo_ue = convocatoria.fondo_ue;
                    activo = convocatoria.activo;
                    fecha_modificacion = convocatoria.fecha_modificacion;
                    if (convocatoria.data_json != null) {
                        // Procesar DatosGeneralesCov
                        // Procesar DatosGeneralesCov.DocumentoCastellano
                        documentoCastellanoNombre = convocatoria.data_json.DatosGeneralesCov.DocumentoCastellano.Nombre;
                        // Procesar DatosGeneralesCov.DocumentoOtraLengua
                        if(convocatoria.data_json.DatosGeneralesCov.DocumentoOtraLengua != null){
                            if(convocatoria.data_json.DatosGeneralesCov.DocumentoOtraLengua.Nombre != null){
                                documentoOtraLenguaNombre = convocatoria.data_json.DatosGeneralesCov.DocumentoOtraLengua.Nombre;
                            }
                        }
                        // Procesar DatosBaseReguladora
                        uRLEspBR = convocatoria.data_json.DatosBaseReguladora.URLEspBR;
                        uRLengBR = convocatoria.data_json.DatosBaseReguladora.URLengBR;
                        // Procesar Datos Solicitud Justificacion Financiacion
                        if (convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Solicitud.InicioSolicitud != null){
                            solicitudInicioSolicitud = convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Solicitud.InicioSolicitud;
                        }
                        if (convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Solicitud.FechaFinSolicitud != null){
                            solicitudFechaFinSolicitud = Date.valueOf(convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Solicitud.FechaFinSolicitud);
                        }
                        if (convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Justificacion.nombre != null){
                            justificacionNombre = convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.Justificacion.nombre;
                        }
                        
                        if (convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.FechaJustificacion != null){
                            fechaJustificacion = Date.valueOf(convocatoria.data_json.DatosSolicitudJustificacionFinanciacion.FechaJustificacion);
                        }
                        // Procesar OtrosDatos
                        if (convocatoria.data_json.OtrosDatos != null) {
                            // ImpactoGenero
                            if (convocatoria.data_json.OtrosDatos.ImpactoGenero != null) {
                                if(convocatoria.data_json.OtrosDatos.ImpactoGenero.codigo != null){
                                    impactoGeneroCodigo = convocatoria.data_json.OtrosDatos.ImpactoGenero.codigo;
                                }
                                if(convocatoria.data_json.OtrosDatos.ImpactoGenero.nombre != null){
                                    impactoGeneroNombre = convocatoria.data_json.OtrosDatos.ImpactoGenero.nombre;
                                }
                            }
                        } else {
                            System.debug('OtrosDatos es nulo');
                        }
                        // Procesar Extractos
                        if (convocatoria.data_json.Extractos != null && convocatoria.data_json.Extractos != null) {
                            for (Convocatoria.Extracto extracto : convocatoria.data_json.Extractos) {
                                if (extracto.ExtractoCastellano != null) {
                                    if(extracto.ExtractoCastellano.TituloExtracto != null){
                                        extractoCastellanoTituloExtracto = extracto.ExtractoCastellano.TituloExtracto;
                                    }
                                    if (extracto.ExtractoCastellano.TextoExtractoCastellano != null) {
                                        textoExtractoCastellano = extracto.ExtractoCastellano.TextoExtractoCastellano.p + '  \n ';
                                    }
                                    if (extracto.ExtractoCastellano.PieFirmaExtracto != null) {
                                        textoExtractoCastellano += extracto.ExtractoCastellano.PieFirmaExtracto.LugarFirma + '  \n ' + extracto.ExtractoCastellano.PieFirmaExtracto.FechaFirma + '  \n ' + extracto.ExtractoCastellano.PieFirmaExtracto.Firmante;
                                    }
                                }
                                if (extracto.ExtractoOtraLengua != null) {
                                    if(extracto.ExtractoOtraLengua.TituloExtracto != null){
                                        extractoOtraLenguaTituloExtracto = extracto.ExtractoOtraLengua.TituloExtracto;
                                    }
                                    if (extracto.ExtractoOtraLengua.TextoExtractoOtraLengua != null) {
                                        textoExtractoOtraLengua = extracto.ExtractoOtraLengua.TextoExtractoOtraLengua.p + '  \n ';
                                    }
                                    if (extracto.ExtractoOtraLengua.PieFirmaExtracto != null) {
                                        textoExtractoOtraLengua += extracto.ExtractoOtraLengua.PieFirmaExtracto.LugarFirma + '  \n ' + extracto.ExtractoOtraLengua.PieFirmaExtracto.FechaFirma + '  \n ' + extracto.ExtractoOtraLengua.PieFirmaExtracto.Firmante;
                                    }
                                }
                                
                                if(extracto.FechaEnvio !=null ){
                                    fechaEnvio = Date.valueOf(extracto.FechaEnvio);
                                }
                                if (extracto.Publicacion != null && extracto.Publicacion.IdExtractoDiarioOficial != null){
                                    publicacionIdExtractoDiarioOficial = extracto.Publicacion.IdExtractoDiarioOficial;
                                }
                                if (extracto.Publicacion != null && extracto.Publicacion.EstadoPublicacion != null && extracto.Publicacion.EstadoPublicacion.Publicado != null) {
                                    if(extracto.Publicacion.EstadoPublicacion.Publicado.FechaPublicacion != null){
                                        publicacionFechaPublicacion = Date.valueOf(extracto.Publicacion.EstadoPublicacion.Publicado.FechaPublicacion);
                                    }
                                    if(extracto.Publicacion.EstadoPublicacion.Publicado.URL != null) {
                                        publicacionUrlPublicacion = extracto.Publicacion.EstadoPublicacion.Publicado.URL;
                                    }
                                }
                            }
                        } else {
                            System.debug('Extractos es nulo o está vacío');
                        }
                        // Procesar OtrosDocumentos
                        if (convocatoria.data_json != null && convocatoria.data_json.OtrosDocumentos != null) {
                            for (Convocatoria.OtrosDocumentos otroDoc : convocatoria.data_json.OtrosDocumentos) {
                                if(otroDoc.DescripcionOtro != null){
                                    otroDocDescripcionOtro = otroDoc.DescripcionOtro;
                                }
                                if (otroDoc.Nombre != null){
                                    otroDocNombre = otroDoc.Nombre;
                                }
                            }
                        } else {
                            System.debug('OtrosDocumentos es nulo');
                        }
                    }
                    String fechaSinOffset = fecha_modificacion.substring(0, 19);
                    String offSet = fecha_modificacion.substring(19, 22);
                    Integer horasOffset = Integer.valueOf(offSet);
                    fechaSinOffset = fechaSinOffset.replace('T', ' ');
                    DateTime fechaModificacion = DateTime.valueOf(fechaSinOffset);
                    fechaModificacion = fechaModificacion.addHours(horasOffset);
                    
                    knowCastellano.code_bdns__c = code_bdns;
                    knowOtraLengua.code_bdns__c = code_bdns;
                    knowCastellano.Descripcion__c = descripcion;
                    knowOtraLengua.Descripcion__c = descripcion;
                    knowCastellano.Importe_total__c = importe_total;
                    knowOtraLengua.Importe_total__c = importe_total;
                    knowCastellano.fondo_ue__c = fondo_ue;
                    knowOtraLengua.fondo_ue__c = fondo_ue;
                    knowCastellano.Activo__c = activo;
                    knowOtraLengua.Activo__c = activo;
                    knowCastellano.NombreDocumentoCastellano__c = documentoCastellanoNombre;
                    knowOtraLengua.NombreDocumentoOtraLengua__c = documentoOtraLenguaNombre;
                    knowCastellano.URLEspBR__c = uRLEspBR;
                    knowOtraLengua.URLEspBR__c = uRLEspBR;
                    knowCastellano.URLengBR__c = uRLengBR;
                    knowOtraLengua.URLengBR__c = uRLengBR;
                    if(solicitudInicioSolicitud != null ){
                        knowCastellano.InicioSolicitud__c = solicitudInicioSolicitud;
                        knowOtraLengua.InicioSolicitud__c = solicitudInicioSolicitud;
                    }
                    if (solicitudFechaFinSolicitud != null){
                        knowCastellano.FechaFinSolicitud__c = solicitudFechaFinSolicitud;
                        knowOtraLengua.FechaFinSolicitud__c = solicitudFechaFinSolicitud;
                    }
                    if(justificacionNombre != null){
                        knowCastellano.NombreJustificacion__c = justificacionNombre;
                        knowOtraLengua.NombreJustificacion__c = justificacionNombre;
                    }
                    
                    if(fechaJustificacion != null){
                        knowCastellano.FechaJustificacion__c = fechaJustificacion;
                        knowOtraLengua.FechaJustificacion__c = fechaJustificacion;
                    }
                    if(impactoGeneroCodigo != null) {
                        knowCastellano.CodigoImpactoGenero__c = impactoGeneroCodigo;
                        knowOtraLengua.CodigoImpactoGenero__c = impactoGeneroCodigo;
                    }
                    if (impactoGeneroNombre != null){
                        knowCastellano.NombreImpactoGenero__c = impactoGeneroNombre;
                        knowOtraLengua.NombreImpactoGenero__c = impactoGeneroNombre;
                    }
                    if (extractoCastellanoTituloExtracto != null){
                        knowCastellano.TituloExtractoCastellano__c = extractoCastellanoTituloExtracto;
                    }
                    if (textoExtractoCastellano != null){
                        knowCastellano.ExtractoCastellano__c = textoExtractoCastellano;
                    }
                    if (extractoOtraLenguaTituloExtracto != null){
                        knowOtraLengua.TituloExtractoOtraLengua__c = extractoOtraLenguaTituloExtracto;
                    }
                    if(textoExtractoOtraLengua != null){
                        knowOtraLengua.ExtractoOtraLengua__c = textoExtractoOtraLengua;
                    }
                    if(otroDocDescripcionOtro != null){
                        knowCastellano.DescripcionOtro__c = otroDocDescripcionOtro;
                        knowOtraLengua.DescripcionOtro__c = otroDocDescripcionOtro;
                    }
                    if(otroDocNombre != null){
                        knowCastellano.NombreOtrosDocumentos__c = otroDocNombre;
                        knowOtraLengua.NombreOtrosDocumentos__c = otroDocNombre;
                    }
                    String convocatoriaRecordTypeID = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Convocatoria').getRecordTypeId();
                    knowCastellano.RecordTypeId = convocatoriaRecordTypeID;
                    if(extractoCastellanoTituloExtracto != null){
                        Integer maxSize = 255;
                        if(extractoCastellanoTituloExtracto.length() > maxSize ){
                            extractoCastellanoTituloExtracto = extractoCastellanoTituloExtracto.substring(0, maxSize);
                        }
                        knowCastellano.Title = extractoCastellanoTituloExtracto ;
                    }else{
                        Integer maxSize = 255;
                        if(descripcion.length() > maxSize ){
                            descripcion = descripcion.substring(0, maxSize);
                        }
                        knowCastellano.Title = descripcion;
                    }
                    if(extractoOtraLenguaTituloExtracto != null){
                        Integer maxSize = 255;
                        if(extractoOtraLenguaTituloExtracto.length() > maxSize ){
                            extractoOtraLenguaTituloExtracto = extractoOtraLenguaTituloExtracto.substring(0, maxSize);
                        }
                        knowOtraLengua.Title = extractoOtraLenguaTituloExtracto;
                    }else {
                        Integer maxSize = 255;
                        if(descripcion.length() > maxSize ){
                            descripcion = descripcion.substring(0, maxSize);
                        }
                        knowOtraLengua.Title = descripcion;
                    }

                    if(fechaEnvio != null){
                        knowCastellano.Fecha_envio_Convocatoria__c = fechaEnvio;
                        knowOtraLengua.Fecha_envio_Convocatoria__c = fechaEnvio;
                    }
                    if(publicacionUrlPublicacion != null){
                        knowCastellano.URL_publicacion_Convocatoria__c = publicacionUrlPublicacion;
                        knowOtraLengua.URL_publicacion_Convocatoria__c = publicacionUrlPublicacion;
                    }
                    if(publicacionIdExtractoDiarioOficial != null){
                        knowCastellano.Id_extracto_diario_oficial_Convocatoria__c = publicacionIdExtractoDiarioOficial;
                        knowOtraLengua.Id_extracto_diario_oficial_Convocatoria__c= publicacionIdExtractoDiarioOficial;
                    }
                    if(publicacionFechaPublicacion != null){
                        knowCastellano.Fecha_publicacion_Convocatoria__c = publicacionFechaPublicacion;
                        knowOtraLengua.Fecha_publicacion_Convocatoria__c = publicacionFechaPublicacion;
                    }
                    knowCastellano.ValidationStatus = 'Validated';
                    knowCastellano.Entidades__c = 'Deputación';
                    knowCastellano.Ambitos__c = 'Transparencia';
                    knowCastellano.UrlName = knowCastellano.code_bdns__c;
                    knowCastellano.Language = 'es';
                    if(fechaModificacion != null){
                        knowCastellano.fecha_modificacion__c = fechaModificacion;
                    }
                    knowOtraLengua.RecordTypeId = convocatoriaRecordTypeID;
                    knowOtraLengua.ValidationStatus = 'Validated';
                    knowOtraLengua.Entidades__c = 'Deputación';
                    knowOtraLengua.Ambitos__c = 'Transparencia';
                    knowOtraLengua.UrlName = knowCastellano.code_bdns__c;
                    knowOtraLengua.Language = 'es_MX';
                    if(fechaModificacion != null){
                        knowOtraLengua.fecha_modificacion__c = fechaModificacion;
                    }
                    if(code_bdns != null){
                        knowCastellano.URL_documentacion_convocatoria__c = 'https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatorias/'+code_bdns;
                        knowOtraLengua.URL_documentacion_convocatoria__c = 'https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatorias/'+code_bdns;
                    }
                    lstKnowledge.add(knowCastellano);
                    lstKnowledge.add(knowOtraLengua);
                    
                    insert lstKnowledge;
                    
                    List<KnowledgeArticleVersion> lstKnowPublish = new List<KnowledgeArticleVersion>();
                    lstKnowPublish = [SELECT Id, KnowledgeArticleId, PublishStatus FROM KnowledgeArticleVersion WHERE PublishStatus = 'Draft'];
                    for(KnowledgeArticleVersion know : lstKnowPublish){
                        KbManagement.PublishingService.publishArticle(know.KnowledgeArticleId, true);
                    }
                }
            } catch (Exception ex) {
                System.debug('Ocurrió un error al procesar la convocatoria: ' + ex.getMessage());
            }
        }
    }
}