force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Ambitos__c.field-meta.xml
<CustomField>
    <fullName>Ambitos__c</fullName>
    <label>Ámbitos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ambitos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>9000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Entidades__c.field-meta.xml
<CustomField>
    <fullName>Entidades__c</fullName>
    <label>Entidad 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_de_actualizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_actualizacion__c</fullName>
    <label>Fecha de actualización</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_de_creacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_creacion__c</fullName>
    <label>Fecha de creación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_del_evento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_del_evento__c</fullName>
    <label>Fecha del evento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Id_externo__c.field-meta.xml
<CustomField>
    <fullName>Id_externo__c</fullName>
    <label>Id externo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Ambitos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cultura y Deportes</fullName>
    </customValue>
    <customValue>
        <fullName>Infraestructuras (Vías y Obras)</fullName>
    </customValue>
    <customValue>
        <fullName>Medio Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Intervención</fullName>
    </customValue>
    <customValue>
        <fullName>Recaudación</fullName>
    </customValue>
    <customValue>
        <fullName>Benestar</fullName>
    </customValue>
    <customValue>
        <fullName>Turismo</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH (Ofertas de empleo)</fullName>
    </customValue>
    <customValue>
        <fullName>Transparencia</fullName>
    </customValue>
    <customValue>
        <fullName>Asesoría Jurídica (legal)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratación</fullName>
    </customValue>
    <customValue>
        <fullName>Tramitación electrónica</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperación</fullName>
    </customValue>
    <customValue>
        <fullName>Asuntos Sociales (Benestar)</fullName>
        <isActive>false</isActive>
        <label>Asuntos Sociales (Benestar)</label>
    </customValue>
    <customValue>
        <fullName>Intervención y Recaudación</fullName>
        <isActive>false</isActive>
        <label>Intervención y Recaudación</label>
    </customValue>
    <masterLabel>Ámbitos</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Deputación</fullName>
        <default>true</default>
        <label>Deputación Provincial de Ourense</label>
    </customValue>
    <customValue>
        <fullName>Provincia</fullName>
    </customValue>
    <customValue>
        <fullName>Allariz</fullName>
    </customValue>
    <customValue>
        <fullName>Amoeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Arnoia A</fullName>
    </customValue>
    <customValue>
        <fullName>Avión</fullName>
    </customValue>
    <customValue>
        <fullName>Baltar</fullName>
    </customValue>
    <customValue>
        <fullName>Bande</fullName>
    </customValue>
    <customValue>
        <fullName>Baños de Molgas</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadás</fullName>
    </customValue>
    <customValue>
        <fullName>Barco de Valdeorras O</fullName>
    </customValue>
    <customValue>
        <fullName>Beade</fullName>
    </customValue>
    <customValue>
        <fullName>Beariz</fullName>
    </customValue>
    <customValue>
        <fullName>Blancos Os</fullName>
    </customValue>
    <customValue>
        <fullName>Boborás</fullName>
    </customValue>
    <customValue>
        <fullName>Bola A</fullName>
    </customValue>
    <customValue>
        <fullName>Bolo O</fullName>
    </customValue>
    <customValue>
        <fullName>Calvos de Randín</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Avia</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Valdeorras</fullName>
    </customValue>
    <customValue>
        <fullName>Carballiño O</fullName>
    </customValue>
    <customValue>
        <fullName>Cartelle</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo de Miño</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo do Val</fullName>
    </customValue>
    <customValue>
        <fullName>Castro Caldelas</fullName>
    </customValue>
    <customValue>
        <fullName>Celanova</fullName>
    </customValue>
    <customValue>
        <fullName>Cenlle</fullName>
    </customValue>
    <customValue>
        <fullName>Chandrexa de Queixa</fullName>
    </customValue>
    <customValue>
        <fullName>Coles</fullName>
    </customValue>
    <customValue>
        <fullName>Cortegada</fullName>
    </customValue>
    <masterLabel>Entidades</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MediatecaApiServiceTest.cls
@isTest
public class MediatecaApiServiceTest {
    @testSetup
    static void setup() {
        // Crear registros de prueba de Knowledge
        Knowledge__kav knowledgeRecord = new Knowledge__kav();
        knowledgeRecord.Id_externo__c = '12345';
        knowledgeRecord.UrlName = '12345';
        knowledgeRecord.Title = 'Test Title';
        knowledgeRecord.Fecha_del_evento__c = DateTime.now();
        knowledgeRecord.Fecha_de_creacion__c = DateTime.now();
        knowledgeRecord.Fecha_de_actualizacion__c = DateTime.now();
        knowledgeRecord.Entidades__c = 'Deputación';
        knowledgeRecord.Ambitos__c = 'Transparencia';
        knowledgeRecord.Descripcion__c = 'Test Description';
        knowledgeRecord.Url__c = 'http://test.com';
        insert knowledgeRecord;
    }
    @isTest
    static void testSyncKnowledgeData() {
        // Simular respuesta HTTP
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        // Configurar el Custom Metadata simulado
        MediatecaApiService.lastSyncMetadata = new Mediateca_Last_Sync__mdt();
        MediatecaApiService.lastSyncMetadata.LastSyncDate__c = DateTime.now().addDays(-1);
        // Iniciar la prueba
        Test.startTest();
        MediatecaApiService.syncKnowledgeData();
        Test.stopTest();
        // Verificar que los registros se han actualizado o insertado correctamente
        List<Knowledge__kav> updatedRecords = [SELECT Id, Id_externo__c, Title FROM Knowledge__kav WHERE Id_externo__c = '12345'];
        System.assert(!updatedRecords.isEmpty(), 'No records found for Id_externo__c = 12345');
        if (!updatedRecords.isEmpty()) {
            Knowledge__kav updatedRecord = updatedRecords[0];
            System.assertEquals('Test Title', updatedRecord.Title, 'Expected: Test Title, Actual: ' + updatedRecord.Title);
        }
        // Verificar la inserción de nuevos registros
        List<Knowledge__kav> newRecords = [SELECT Id, Id_externo__c, Title FROM Knowledge__kav WHERE Id_externo__c = '67890'];
        System.assert(newRecords.isEmpty(), 'No records found for Id_externo__c = 67890');
        if (!newRecords.isEmpty()) {
            Knowledge__kav newRecord = newRecords[0];
            System.assertEquals('New Title', newRecord.Title, 'Expected: New Title, Actual: ' + newRecord.Title);
        }
    }
    
    @isTest
    static void testParseDateTime() {
        String dateTimeString = '2023-07-21T10:30:00Z';
        DateTime expectedDateTime = DateTime.newInstance(2023, 7, 21, 10, 30, 0);
        DateTime actualDateTime = MediatecaApiService.parseDateTime(dateTimeString);
        System.assertEquals(expectedDateTime, actualDateTime);
        // Prueba para cadena de fecha con longitud mayor a 19
        dateTimeString = '2023-07-21T10:30:00.123Z';
        expectedDateTime = DateTime.newInstance(2023, 7, 21, 10, 30, 0);
        actualDateTime = MediatecaApiService.parseDateTime(dateTimeString);
        System.assertEquals(expectedDateTime, actualDateTime);
    }
    @isTest
    static void testConvertToSpanishTime() {
        DateTime dateTimeUtc = DateTime.newInstanceGmt(2023, 7, 21, 10, 30, 0);
        DateTime expectedDateTime = DateTime.newInstance(2023, 7, 21, 12, 30, 0); // UTC+2 para la hora de verano
        DateTime actualDateTime = MediatecaApiService.convertToSpanishTime(dateTimeUtc);
        System.assertEquals(expectedDateTime.addHours(2), actualDateTime);
    }
    @isTest
    static void testFormatDateTimeForApi() {
        DateTime d = DateTime.newInstance(2023, 7, 21, 10, 30, 0);
        String expectedFormattedDateTime = '2023-07-21T10:30:00+02:00'; // Formato esperado
        String actualFormattedDateTime = MediatecaApiService.formatDateTimeForApi(d);
        System.assertEquals(expectedFormattedDateTime, actualFormattedDateTime);
    }
}