force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Ambitos__c.field-meta.xml
<CustomField>
    <fullName>Ambitos__c</fullName>
    <label>Ámbitos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ambitos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>9000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Entidades__c.field-meta.xml
<CustomField>
    <fullName>Entidades__c</fullName>
    <label>Entidad 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_de_creacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_creacion__c</fullName>
    <label>Fecha de creación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/fecha_modificacion__c.field-meta.xml
<CustomField>
    <fullName>fecha_modificacion__c</fullName>
    <label>Fecha modificación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_codigo__c.field-meta.xml
<CustomField>
    <fullName>Tramite_codigo__c</fullName>
    <label>Trámite código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_codigo_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_codigo_espanol__c</fullName>
    <label>Trámite código español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_codigo_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_codigo_galego__c</fullName>
    <label>Trámite código galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_coleccion_normativas_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_coleccion_normativas_espanol__c</fullName>
    <label>Trámite colección normativas español</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_coleccion_normativas_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_coleccion_normativas_galego__c</fullName>
    <label>Trámite colección normativas galego</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_descripcion_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_descripcion_espanol__c</fullName>
    <label>Trámite descripción español</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_descripcion_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_descripcion_galego__c</fullName>
    <label>Trámite descripción galego</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_efecto_silencio_admin_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_efecto_silencio_admin_espanol__c</fullName>
    <label>Trámite efecto silencio admin español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_efecto_silencio_admin_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_efecto_silencio_admin_galego__c</fullName>
    <label>Trámite efecto silencio admin galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_finalidad_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_finalidad_espanol__c</fullName>
    <label>Trámite finalidad español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_finalidad_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_finalidad_galego__c</fullName>
    <label>Trámite finalidad galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_id__c.field-meta.xml
<CustomField>
    <fullName>Tramite_id__c</fullName>
    <label>Trámite id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_informacion_adicional_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_informacion_adicional_espanol__c</fullName>
    <label>Trámite información adicional español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_informacion_adicional_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_informacion_adicional_galego__c</fullName>
    <label>Trámite información adicional galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_nivel_identificacion_sol_esp__c.field-meta.xml
<CustomField>
    <fullName>Tramite_nivel_identificacion_sol_esp__c</fullName>
    <label>Trámite nivel identificación sol español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_normativa_basica_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_normativa_basica_espanol__c</fullName>
    <label>Trámite normativa básica español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_normativa_basica_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_normativa_basica_galego__c</fullName>
    <label>Trámite normativa básica galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_organo_gestor_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_organo_gestor_espanol__c</fullName>
    <label>Trámite órgano gestor español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_organo_gestor_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_organo_gestor_galego__c</fullName>
    <label>Trámite órgano gestor galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_plazo_presentacion_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_plazo_presentacion_espanol__c</fullName>
    <label>Trámite plazo presentación español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_plazo_presentacion_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_plazo_presentacion_galego__c</fullName>
    <label>Trámite plazo presentación galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_plazo_resolucion_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_plazo_resolucion_espanol__c</fullName>
    <label>Trámite plazo resolución español</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_plazo_resolucion_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_plazo_resolucion_galego__c</fullName>
    <label>Trámite plazo resolución galego</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_presentacion_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_presentacion_espanol__c</fullName>
    <label>Trámite presentación español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_presentacion_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_presentacion_galego__c</fullName>
    <label>Trámite presentación galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_presentar_por_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_presentar_por_espanol__c</fullName>
    <label>Trámite presentar por español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_presentar_por_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_presentar_por_galego__c</fullName>
    <label>Trámite presentar por galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_recursos_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_recursos_espanol__c</fullName>
    <label>Trámite recursos español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_recursos_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_recursos_galego__c</fullName>
    <label>Trámite recursos galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_requisitos_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_requisitos_espanol__c</fullName>
    <label>Trámite requisitos español</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_requisitos_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_requisitos_galego__c</fullName>
    <label>Trámite requisitos galego</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_titulo_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_titulo_espanol__c</fullName>
    <label>Trámite título español</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_titulo_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_titulo_galego__c</fullName>
    <label>Trámite título galego</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_descarga_instancia_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_descarga_instancia_espanol__c</fullName>
    <label>Trámite url descarga instancia español</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_descarga_instancia_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_descarga_instancia_galego__c</fullName>
    <label>Trámite url descarga instancia galego</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_detalle_tramite_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_detalle_tramite_espanol__c</fullName>
    <label>Trámite url detalle trámite español</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_detalle_tramite_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_detalle_tramite_galego__c</fullName>
    <label>Trámite url detalle trámite galego</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_inicio_tramitacion_espanol__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_inicio_tramitacion_espanol__c</fullName>
    <label>Trámite url inicio tramitación español</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tramite_url_inicio_tramitacion_galego__c.field-meta.xml
<CustomField>
    <fullName>Tramite_url_inicio_tramitacion_galego__c</fullName>
    <label>Trámite url inicio tramitación galego</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Tramite.recordType-meta.xml
<RecordType>
    <fullName>Tramite</fullName>
    <active>true</active>
    <label>Trámite</label>
</RecordType>

force-app/main/default/globalValueSets/Ambitos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cultura y Deportes</fullName>
    </customValue>
    <customValue>
        <fullName>Infraestructuras (Vías y Obras)</fullName>
    </customValue>
    <customValue>
        <fullName>Medio Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Intervención</fullName>
    </customValue>
    <customValue>
        <fullName>Recaudación</fullName>
    </customValue>
    <customValue>
        <fullName>Benestar</fullName>
    </customValue>
    <customValue>
        <fullName>Turismo</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH (Ofertas de empleo)</fullName>
    </customValue>
    <customValue>
        <fullName>Transparencia</fullName>
    </customValue>
    <customValue>
        <fullName>Asesoría Jurídica (legal)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratación</fullName>
    </customValue>
    <customValue>
        <fullName>Tramitación electrónica</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperación</fullName>
    </customValue>
    <customValue>
        <fullName>Asuntos Sociales (Benestar)</fullName>
        <isActive>false</isActive>
        <label>Asuntos Sociales (Benestar)</label>
    </customValue>
    <customValue>
        <fullName>Intervención y Recaudación</fullName>
        <isActive>false</isActive>
        <label>Intervención y Recaudación</label>
    </customValue>
    <masterLabel>Ámbitos</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Deputación</fullName>
        <default>true</default>
        <label>Deputación Provincial de Ourense</label>
    </customValue>
    <customValue>
        <fullName>Provincia</fullName>
    </customValue>
    <customValue>
        <fullName>Allariz</fullName>
    </customValue>
    <customValue>
        <fullName>Amoeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Arnoia A</fullName>
    </customValue>
    <customValue>
        <fullName>Avión</fullName>
    </customValue>
    <customValue>
        <fullName>Baltar</fullName>
    </customValue>
    <customValue>
        <fullName>Bande</fullName>
    </customValue>
    <customValue>
        <fullName>Baños de Molgas</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadás</fullName>
    </customValue>
    <customValue>
        <fullName>Barco de Valdeorras O</fullName>
    </customValue>
    <customValue>
        <fullName>Beade</fullName>
    </customValue>
    <customValue>
        <fullName>Beariz</fullName>
    </customValue>
    <customValue>
        <fullName>Blancos Os</fullName>
    </customValue>
    <customValue>
        <fullName>Boborás</fullName>
    </customValue>
    <customValue>
        <fullName>Bola A</fullName>
    </customValue>
    <customValue>
        <fullName>Bolo O</fullName>
    </customValue>
    <customValue>
        <fullName>Calvos de Randín</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Avia</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Valdeorras</fullName>
    </customValue>
    <customValue>
        <fullName>Carballiño O</fullName>
    </customValue>
    <customValue>
        <fullName>Cartelle</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo de Miño</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo do Val</fullName>
    </customValue>
    <customValue>
        <fullName>Castro Caldelas</fullName>
    </customValue>
    <customValue>
        <fullName>Celanova</fullName>
    </customValue>
    <customValue>
        <fullName>Cenlle</fullName>
    </customValue>
    <customValue>
        <fullName>Chandrexa de Queixa</fullName>
    </customValue>
    <customValue>
        <fullName>Coles</fullName>
    </customValue>
    <customValue>
        <fullName>Cortegada</fullName>
    </customValue>
    <masterLabel>Entidades</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TramiteService.cls
public class TramiteService {
    public static void procesarTramite(List<String> detallesJson){
        for (String jsonDetalle : detallesJson){
            try {
                //Declaracion de variables
                Knowledge__kav knowCastellano = new Knowledge__kav();
                Knowledge__kav knowOtraLengua = new Knowledge__kav();
                List<Knowledge__kav> lstKnowledge = new List<Knowledge__kav>();
                
                Integer tramiteId;
                String fecha_creacion;
                String fecha_modificacion;
                String entidad;
                //Variables data_es_json
                String data_es_json_coleccionNormativas;
                String data_es_json_urlInicioTramitacion;
                String data_es_json_urlDescargaInstancia;
                
                //Variables data_gl_json
                String data_gl_json_coleccionNormativas;
                String data_gl_json_urlInicioTramitacion;
                String data_gl_json_urlDescargaInstancia;
                
                // Deserializa el JSON en un objeto de tramite
                Tramite tramite = (Tramite) JSON.deserialize(jsonDetalle, Tramite.class);
                // Procesar los datos principales del tramite
                if(tramite != null){
                    tramiteId = tramite.id; // parsear a text
                    String stringTramiteId = String.valueOf(tramiteId);
                    knowCastellano.Tramite_id__c = stringTramiteId;
                    knowOtraLengua.Tramite_id__c = stringTramiteId;
                    knowCastellano.UrlName = stringTramiteId;
                    knowOtraLengua.UrlName = stringTramiteId;
                    
                    knowCastellano.Tramite_codigo__c = tramite.codigo;
                    knowOtraLengua.Tramite_codigo__c = tramite.codigo;
                    
                    knowCastellano.Title  = tramite.titulo;
                    knowOtraLengua.Title  = tramite.titulo;
                    
                    knowCastellano.Descripcion__c  = tramite.descripcion;
                    knowOtraLengua.Descripcion__c  = tramite.descripcion;
                    
                    knowCastellano.Ambitos__c = tramite.tema.name;
                    knowOtraLengua.Ambitos__c = tramite.tema.name;
                    
                    entidad = tramite.institucion.name;
                    if(entidad.contains(',')){
                        entidad.replace(',', ' ');
                    }
                    knowCastellano.Entidades__c = entidad;
                    knowOtraLengua.Entidades__c = entidad;
                    
                    knowCastellano.Activo__c = tramite.activo;
                    knowOtraLengua.Activo__c = tramite.activo;
                    
                    fecha_creacion = tramite.fecha_creacion;
                    fecha_modificacion = tramite.fecha_modificacion;
                    // Procesar data_es_json del Tramite
                    if(tramite.data_es_json != null){
                        if(tramite.data_es_json.codigo != null){
                            knowCastellano.Tramite_codigo_espanol__c = tramite.data_es_json.codigo;
                        }
                        if(tramite.data_es_json.titulo != null){
                            knowCastellano.Tramite_titulo_espanol__c = tramite.data_es_json.titulo;
                        }
                        if(tramite.data_es_json.descripcion != null){
                            knowCastellano.Tramite_descripcion_espanol__c = tramite.data_es_json.descripcion;
                        }
                        if(tramite.data_es_json.finalidad != null){
                            knowCastellano.Tramite_finalidad_espanol__c = tramite.data_es_json.finalidad;
                        }
                        if(tramite.data_es_json.requisitos != null){
                            knowCastellano.Tramite_requisitos_espanol__c = tramite.data_es_json.requisitos;
                        }
                        if(tramite.data_es_json.plazoPresentacion != null){
                            knowCastellano.Tramite_plazo_presentacion_espanol__c = tramite.data_es_json.plazoPresentacion;
                        }
                        if(tramite.data_es_json.presentacion != null){
                            knowCastellano.Tramite_presentacion_espanol__c = tramite.data_es_json.presentacion;
                        }
                        if(tramite.data_es_json.presentarPor != null){
                            knowCastellano.Tramite_presentar_por_espanol__c = tramite.data_es_json.presentarPor;
                        }
                        if(tramite.data_es_json.organoGestor != null){
                            knowCastellano.Tramite_organo_gestor_espanol__c = tramite.data_es_json.organoGestor;
                        }
                        if(tramite.data_es_json.plazoResolucion != null){
                            knowCastellano.Tramite_plazo_resolucion_espanol__c = tramite.data_es_json.plazoResolucion;
                        }
                        if(tramite.data_es_json.efectoSilencioAdministrativo != null){
                            knowCastellano.Tramite_efecto_silencio_admin_espanol__c = tramite.data_es_json.efectoSilencioAdministrativo;
                        }
                        if(tramite.data_es_json.recursos != null){
                            knowCastellano.Tramite_recursos_espanol__c = tramite.data_es_json.recursos;
                        }
                        if(tramite.data_es_json.normativaBasica != null){
                            knowCastellano.Tramite_normativa_basica_espanol__c = tramite.data_es_json.normativaBasica;
                        }
                        
                        if(tramite.data_es_json.coleccionNormativas != null){
                            data_es_json_coleccionNormativas = '';
                            for(Tramite.cls_coleccionNormativas coleccionNormativas : tramite.data_es_json.coleccionNormativas){
                                if(coleccionNormativas.titulo != null){
                                    data_es_json_coleccionNormativas += 'Titulo: '+' '+ coleccionNormativas.titulo + '  \n ';
                                }
                                if(coleccionNormativas.url != null){
                                    data_es_json_coleccionNormativas += 'Url: ' +' '+ coleccionNormativas.url;
                                    data_es_json_coleccionNormativas += '  \n ';
                                }
                            }
                        }
                        if(data_es_json_coleccionNormativas!= null){
                            knowCastellano.Tramite_coleccion_normativas_espanol__c = data_es_json_coleccionNormativas;
                        }
                        if(tramite.data_es_json.informacionAdicional != null){
                            knowCastellano.Tramite_informacion_adicional_espanol__c = tramite.data_es_json.informacionAdicional;
                        }
                        if(tramite.data_es_json.nivelIdentificacionSolicitante != null){
                            knowCastellano.Tramite_nivel_identificacion_sol_esp__c = tramite.data_es_json.nivelIdentificacionSolicitante;
                        }
                        if(tramite.data_es_json.urlInicioTramitacion != null){
                            knowCastellano.Tramite_url_inicio_tramitacion_espanol__c = tramite.data_es_json.urlInicioTramitacion;
                        }
                        if(tramite.data_es_json.urlInicioTramitacion != null){
                            data_es_json_urlInicioTramitacion = tramite.data_es_json.urlInicioTramitacion;
                            if(tramite.data_es_json.urlDescargaInstancia != null){
                                data_es_json_urlDescargaInstancia = data_es_json_urlInicioTramitacion+tramite.data_es_json.urlDescargaInstancia;
                            }
                        }
                        if(data_es_json_urlDescargaInstancia != null){
                            knowCastellano.Tramite_url_descarga_instancia_espanol__c = data_es_json_urlDescargaInstancia;
                        }
                        if(tramite.data_es_json.urlDetalleTramite != null){
                            knowCastellano.Tramite_url_detalle_tramite_espanol__c = tramite.data_es_json.urlDetalleTramite;
                        }
                    } else{
                        System.debug('data_es_json es nulo o está vacío');
                    }
                    // Procesar data_gl_json del Tramite
                    if(tramite.data_gl_json != null){
                        if(tramite.data_gl_json.codigo != null){
                            knowOtraLengua.Tramite_codigo_galego__c = tramite.data_gl_json.codigo;
                        }
                        if(tramite.data_gl_json.titulo != null){
                            knowOtraLengua.Tramite_titulo_galego__c = tramite.data_gl_json.titulo;
                        }
                        if(tramite.data_gl_json.descripcion != null){
                            knowOtraLengua.Tramite_descripcion_galego__c = tramite.data_gl_json.descripcion;
                        }
                        if(tramite.data_gl_json.finalidad != null){
                            knowOtraLengua.Tramite_finalidad_galego__c = tramite.data_gl_json.finalidad;
                        }
                        if(tramite.data_gl_json.requisitos != null){
                            knowOtraLengua.Tramite_requisitos_galego__c = tramite.data_gl_json.requisitos;
                        }
                        if(tramite.data_gl_json.plazoPresentacion != null){
                            knowOtraLengua.Tramite_plazo_presentacion_galego__c = tramite.data_gl_json.plazoPresentacion;
                        }
                        if(tramite.data_gl_json.presentacion != null){
                            knowOtraLengua.Tramite_presentacion_galego__c = tramite.data_gl_json.presentacion;
                        }
                        if(tramite.data_gl_json.presentarPor != null){
                            knowOtraLengua.Tramite_presentar_por_galego__c = tramite.data_gl_json.presentarPor;
                        }
                        if(tramite.data_gl_json.organoGestor != null){
                            knowOtraLengua.Tramite_organo_gestor_galego__c = tramite.data_gl_json.organoGestor;
                        }
                        if(tramite.data_gl_json.plazoResolucion != null){
                            knowOtraLengua.Tramite_plazo_resolucion_galego__c = tramite.data_gl_json.plazoResolucion;
                        }
                        if(tramite.data_gl_json.efectoSilencioAdministrativo != null){
                            knowOtraLengua.Tramite_efecto_silencio_admin_galego__c = tramite.data_gl_json.efectoSilencioAdministrativo;
                        }
                        if(tramite.data_gl_json.recursos != null){
                            knowOtraLengua.Tramite_recursos_galego__c = tramite.data_gl_json.recursos;
                        }
                        if(tramite.data_gl_json.normativaBasica != null){
                            knowOtraLengua.Tramite_normativa_basica_galego__c = tramite.data_gl_json.normativaBasica;
                        }
                        
                        if(tramite.data_gl_json.coleccionNormativas != null){
                            data_gl_json_coleccionNormativas = '';
                            for(Tramite.cls_coleccionNormativas coleccionNormativas : tramite.data_gl_json.coleccionNormativas){
                                if(coleccionNormativas.titulo != null){
                                    data_gl_json_coleccionNormativas += 'Titulo: '+' '+ coleccionNormativas.titulo + '  \n ';
                                }
                                if(coleccionNormativas.url != null){
                                    data_gl_json_coleccionNormativas += 'Url: ' +' '+ coleccionNormativas.url;
                                    data_gl_json_coleccionNormativas += '  \n ';
                                }
                            }
                        }
                        if(data_gl_json_coleccionNormativas!= null){
                            knowOtraLengua.Tramite_coleccion_normativas_galego__c = data_gl_json_coleccionNormativas;
                        }
                        if(tramite.data_gl_json.informacionAdicional != null){
                            knowOtraLengua.Tramite_informacion_adicional_galego__c = tramite.data_gl_json.informacionAdicional;
                        }
                        if(tramite.data_gl_json.nivelIdentificacionSolicitante != null){
                            knowOtraLengua.Tramite_nivel_identificacion_sol_esp__c = tramite.data_gl_json.nivelIdentificacionSolicitante;
                        }
                        if(tramite.data_gl_json.urlInicioTramitacion != null){
                            knowOtraLengua.Tramite_url_inicio_tramitacion_galego__c = tramite.data_gl_json.urlInicioTramitacion;
                        }
                        if(tramite.data_gl_json.urlInicioTramitacion != null){
                            data_gl_json_urlInicioTramitacion = tramite.data_gl_json.urlInicioTramitacion;
                            if(tramite.data_gl_json.urlDescargaInstancia != null){
                                data_gl_json_urlDescargaInstancia = data_gl_json_urlInicioTramitacion+tramite.data_gl_json.urlDescargaInstancia;
                            }
                        }
                        if(data_gl_json_urlDescargaInstancia != null){
                            knowOtraLengua.Tramite_url_descarga_instancia_galego__c = data_gl_json_urlDescargaInstancia;
                        }
                        if(tramite.data_gl_json.urlDetalleTramite != null){
                            knowOtraLengua.Tramite_url_detalle_tramite_galego__c = tramite.data_gl_json.urlDetalleTramite;
                        }
                    } else {
                        System.debug('data_gl_json es nulo o está vacío');
                    }
                    //Fecha creacion
                    if(fecha_creacion != null){
                        String fechaCreacionSinOffset = fecha_creacion.substring(0, 19);
                        String offSetCreacion = fecha_creacion.substring(19, 22);
                        Integer horasOffsetCreacion = Integer.valueOf(offSetCreacion);
                        fechaCreacionSinOffset = fechaCreacionSinOffset.replace('T', ' ');
                        DateTime fechaCreacion = DateTime.valueOf(fechaCreacionSinOffset);
                        fechaCreacion = fechaCreacion.addHours(horasOffsetCreacion);
                        knowCastellano.Fecha_de_creacion__c = fechaCreacion;
                        knowOtraLengua.Fecha_de_creacion__c = fechaCreacion;
                        System.debug('Fecha creacion: '+ fechaCreacion);
                    }
                    //Fecha modificacion
                    if(fecha_modificacion != null){
                        String fechaModificacionSinOffset = fecha_modificacion.substring(0, 19);
                        String offSetModificacion = fecha_modificacion.substring(19, 22);
                        Integer horasOffsetModificacion = Integer.valueOf(offSetModificacion);
                        fechaModificacionSinOffset = fechaModificacionSinOffset.replace('T', ' ');
                        DateTime fechaModificacion = DateTime.valueOf(fechaModificacionSinOffset);
                        fechaModificacion = fechaModificacion.addHours(horasOffsetModificacion);
                        knowCastellano.fecha_modificacion__c = fechaModificacion;
                        knowOtraLengua.fecha_modificacion__c = fechaModificacion;
                        System.debug('Fecha modificacion: '+ fechaModificacion);
                    }
                    knowCastellano.ValidationStatus = 'Validated';
                    knowOtraLengua.ValidationStatus = 'Validated';
                    knowCastellano.Language = 'es';
                    knowOtraLengua.Language = 'es_MX';
                    String tramiteRecordTypeID = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByDeveloperName().get('Tramite').getRecordTypeId();
                    knowCastellano.RecordTypeId = tramiteRecordTypeID;
                    knowOtraLengua.RecordTypeId = tramiteRecordTypeID;
                    lstKnowledge.add(knowCastellano);
                    lstKnowledge.add(knowOtraLengua);
                    insert lstKnowledge;
                    
                    List<KnowledgeArticleVersion> lstKnowPublish = new List<KnowledgeArticleVersion>();
                    lstKnowPublish = [SELECT Id, KnowledgeArticleId, PublishStatus FROM KnowledgeArticleVersion WHERE PublishStatus = 'Draft'];
                    for(KnowledgeArticleVersion know : lstKnowPublish){
                        KbManagement.PublishingService.publishArticle(know.KnowledgeArticleId, true);
                    }
                    
                } else {
                    System.debug('El objeto tramite es nulo o vacio');
                }
            } catch(Exception ex) {
                System.debug('Ocurrió un error al procesar el tramite: ' + ex.getMessage());
            }
        }
    }
}