force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Ambitos__c.field-meta.xml
<CustomField>
    <fullName>Ambitos__c</fullName>
    <label>Ámbitos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ambitos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Bop_Id__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Bop_Id__c</fullName>
    <label>Bop Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_bop_id_bop_externo__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_bop_id_bop_externo__c</fullName>
    <label>Id bop externo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_entidad_nif_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_entidad_nif_Esp__c</fullName>
    <label>Entidad nif</label>
    <length>27</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_entidad_nif_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_entidad_nif_Gal__c</fullName>
    <label>Entidad nif</label>
    <length>27</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_entidad_nombre_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_entidad_nombre_Esp__c</fullName>
    <label>Entidad nombre</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_entidad_nombre_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_entidad_nombre_Gal__c</fullName>
    <label>Entidad nombre</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_fecha_entrada_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_fecha_entrada_Esp__c</fullName>
    <label>Fecha entrada</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_fecha_entrada_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_fecha_entrada_Gal__c</fullName>
    <label>Fecha entrada</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Id__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Id__c</fullName>
    <label>Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Id_bop_edicto_externo__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Id_bop_edicto_externo__c</fullName>
    <label>Id bop edicto externo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Id_bop_edicto_externo_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Id_bop_edicto_externo_Esp__c</fullName>
    <label>Id bop edicto externo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Id_bop_edicto_externo_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Id_bop_edicto_externo_Gal__c</fullName>
    <label>Id bop edicto externo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_numero_pagina_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_numero_pagina_Esp__c</fullName>
    <label>Número página</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_numero_pagina_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_numero_pagina_Gal__c</fullName>
    <label>Número página</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_sumario_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_sumario_Esp__c</fullName>
    <label>Sumario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_sumario_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_sumario_Gal__c</fullName>
    <label>Sumario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_texto_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_texto_Esp__c</fullName>
    <label>Texto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_texto_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_texto_Gal__c</fullName>
    <label>Texto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_epub_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_epub_Esp__c</fullName>
    <label>Url epub</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_epub_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_epub_Gal__c</fullName>
    <label>Url epub</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_html_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_html_Esp__c</fullName>
    <label>Url html</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_html_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_html_Gal__c</fullName>
    <label>Url html</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_pdf_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_pdf_Esp__c</fullName>
    <label>Url pdf</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_pdf_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_pdf_Gal__c</fullName>
    <label>Url pdf</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_texto_Esp__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_texto_Esp__c</fullName>
    <label>Url texto</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Bopedicto_Url_texto_Gal__c.field-meta.xml
<CustomField>
    <fullName>Bopedicto_Url_texto_Gal__c</fullName>
    <label>Url texto</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>9000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Entidades__c.field-meta.xml
<CustomField>
    <fullName>Entidades__c</fullName>
    <label>Entidad 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Fecha_de_creacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_creacion__c</fullName>
    <label>Fecha de creación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/fecha_modificacion__c.field-meta.xml
<CustomField>
    <fullName>fecha_modificacion__c</fullName>
    <label>Fecha modificación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Sumario__c.field-meta.xml
<CustomField>
    <fullName>Sumario__c</fullName>
    <label>Sumario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Bopedicto.recordType-meta.xml
<RecordType>
    <fullName>Bopedicto</fullName>
    <active>true</active>
    <label>Bopedicto</label>
</RecordType>

force-app/main/default/globalValueSets/Ambitos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cultura y Deportes</fullName>
    </customValue>
    <customValue>
        <fullName>Infraestructuras (Vías y Obras)</fullName>
    </customValue>
    <customValue>
        <fullName>Medio Ambiente</fullName>
    </customValue>
    <customValue>
        <fullName>Intervención</fullName>
    </customValue>
    <customValue>
        <fullName>Recaudación</fullName>
    </customValue>
    <customValue>
        <fullName>Benestar</fullName>
    </customValue>
    <customValue>
        <fullName>Turismo</fullName>
    </customValue>
    <customValue>
        <fullName>RRHH (Ofertas de empleo)</fullName>
    </customValue>
    <customValue>
        <fullName>Transparencia</fullName>
    </customValue>
    <customValue>
        <fullName>Asesoría Jurídica (legal)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratación</fullName>
    </customValue>
    <customValue>
        <fullName>Tramitación electrónica</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperación</fullName>
    </customValue>
    <customValue>
        <fullName>Asuntos Sociales (Benestar)</fullName>
        <isActive>false</isActive>
        <label>Asuntos Sociales (Benestar)</label>
    </customValue>
    <customValue>
        <fullName>Intervención y Recaudación</fullName>
        <isActive>false</isActive>
        <label>Intervención y Recaudación</label>
    </customValue>
    <masterLabel>Ámbitos</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Entidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Deputación</fullName>
        <default>true</default>
        <label>Deputación Provincial de Ourense</label>
    </customValue>
    <customValue>
        <fullName>Provincia</fullName>
    </customValue>
    <customValue>
        <fullName>Allariz</fullName>
    </customValue>
    <customValue>
        <fullName>Amoeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Arnoia A</fullName>
    </customValue>
    <customValue>
        <fullName>Avión</fullName>
    </customValue>
    <customValue>
        <fullName>Baltar</fullName>
    </customValue>
    <customValue>
        <fullName>Bande</fullName>
    </customValue>
    <customValue>
        <fullName>Baños de Molgas</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadás</fullName>
    </customValue>
    <customValue>
        <fullName>Barco de Valdeorras O</fullName>
    </customValue>
    <customValue>
        <fullName>Beade</fullName>
    </customValue>
    <customValue>
        <fullName>Beariz</fullName>
    </customValue>
    <customValue>
        <fullName>Blancos Os</fullName>
    </customValue>
    <customValue>
        <fullName>Boborás</fullName>
    </customValue>
    <customValue>
        <fullName>Bola A</fullName>
    </customValue>
    <customValue>
        <fullName>Bolo O</fullName>
    </customValue>
    <customValue>
        <fullName>Calvos de Randín</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Avia</fullName>
    </customValue>
    <customValue>
        <fullName>Carballeda de Valdeorras</fullName>
    </customValue>
    <customValue>
        <fullName>Carballiño O</fullName>
    </customValue>
    <customValue>
        <fullName>Cartelle</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo de Miño</fullName>
    </customValue>
    <customValue>
        <fullName>Castrelo do Val</fullName>
    </customValue>
    <customValue>
        <fullName>Castro Caldelas</fullName>
    </customValue>
    <customValue>
        <fullName>Celanova</fullName>
    </customValue>
    <customValue>
        <fullName>Cenlle</fullName>
    </customValue>
    <customValue>
        <fullName>Chandrexa de Queixa</fullName>
    </customValue>
    <customValue>
        <fullName>Coles</fullName>
    </customValue>
    <customValue>
        <fullName>Cortegada</fullName>
    </customValue>
    <masterLabel>Entidades</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BopedictoService.cls
public class BopedictoService {
    public static void procesarBopedicto(List<String> detallesJson){
        for (String jsonDetalle : detallesJson){
            try {
                //Declaracion de variables
                Knowledge__kav knowCastellano = new Knowledge__kav();
                Knowledge__kav knowOtraLengua = new Knowledge__kav();
                List<Knowledge__kav> lstKnowledge = new List<Knowledge__kav>();
                String fecha_creacion;
                Datetime fechaCreacion;
                String fecha_modificacion;
                Datetime fechaModificacion;
                String ambito; //tema_name
                String entidad; // ambito_name
                Datetime fechaEntradaEspanol;
                Datetime fechaEntradaGalego;
                
                //Variable recordType
                String bopedictoRecordTypeID = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByDeveloperName().get('Bopedicto').getRecordTypeId();
                
                // Deserializa el JSON en un objeto de Bopedicto
                Bopedicto bopedicto = Bopedicto.fromJson(jsonDetalle);
                // Procesar los datos principales del bopedicto
                if(bopedicto != null){
                    fecha_creacion = bopedicto.fecha_creacion;
                    fecha_modificacion = bopedicto.fecha_modificacion;
                    if(fecha_modificacion != null){
                        fechaModificacion = convertFechasJson(fecha_modificacion);
                    }else{
                        System.debug('fecha_modificacion es null');
                    }
                    if(fecha_creacion != null){
                        fechaCreacion = convertFechasJson(fecha_creacion);
                    }else{
                        System.debug('fecha_creacion es null');
                    }
                    if(bopedicto.tema != null){
                        ambito = bopedicto.tema.name;
                    }else{
                        ambito = 'Otras';
                    }
                    if(bopedicto.ambito != null){
                        entidad = bopedicto.ambito.name;
                    }else {
                        entidad = 'Deputación';
                    }
                    if(entidad.contains('Diputación')){
                        entidad = 'Deputación';
                    }
                    if(entidad.contains(',')){
                        entidad = entidad.replace(',', '');
                    }
                    if(bopedicto.data_es_json != null){
                        knowCastellano.Bopedicto_Id__c = String.valueOf(bopedicto.id);
                        knowCastellano.UrlName = String.valueOf(bopedicto.id)+'-'+'Esp';
                        knowCastellano.Bopedicto_Id_bop_edicto_externo__c = String.valueOf(bopedicto.id_bop_edicto_externo);
                        knowCastellano.Sumario__c = bopedicto.sumario;
                        knowCastellano.Activo__c = bopedicto.activo;
                        knowCastellano.Bopedicto_Bop_Id__c = String.valueOf(bopedicto.bop.Id); //Convert to String
                        knowCastellano.Bopedicto_bop_id_bop_externo__c = String.valueOf(bopedicto.bop.id_bop_externo); //Convert to String
                        knowCastellano.Ambitos__c = ambito;
                        knowCastellano.Entidades__c = entidad;
                        if(fecha_creacion != null){
                            knowCastellano.Fecha_de_creacion__c = fechaCreacion;
                        }
                        if(fecha_modificacion != null){
                            knowCastellano.fecha_modificacion__c = fechaModificacion;
                        }
                        
                        if(bopedicto.data_es_json.id_bop_edicto_externo != null){
                            knowCastellano.Bopedicto_Id_bop_edicto_externo_Esp__c = String.valueOf(bopedicto.data_es_json.id_bop_edicto_externo);//Convert to String
                        }
                        if(bopedicto.data_es_json.fecha_entrada != null){
                            fechaEntradaEspanol = convertFechasJson(bopedicto.data_es_json.fecha_entrada);
                            knowCastellano.Bopedicto_fecha_entrada_Esp__c = fechaEntradaEspanol;
                        }
                        if(bopedicto.data_es_json.numero_pagina != null){
                            knowCastellano.Bopedicto_numero_pagina_Esp__c = bopedicto.data_es_json.numero_pagina;
                        }
                        if(bopedicto.data_es_json.entidad_nombre != null){
                            knowCastellano.Bopedicto_entidad_nombre_Esp__c = bopedicto.data_es_json.entidad_nombre;
                        }
                        if(bopedicto.data_es_json.entidad_nif != null){
                            knowCastellano.Bopedicto_entidad_nif_Esp__c = bopedicto.data_es_json.entidad_nif;
                        }
                        if(bopedicto.data_es_json.sumario != null){
                            knowCastellano.Bopedicto_sumario_Esp__c = bopedicto.data_es_json.sumario;
                            knowCastellano.Title = bopedicto.data_es_json.sumario;
                            knowCastellano.Descripcion__c = bopedicto.data_es_json.sumario;
                        }else {
                            knowCastellano.Title = bopedicto.sumario;
                            knowCastellano.Descripcion__c = bopedicto.sumario;
                        }
                        if(bopedicto.data_es_json.texto != null){
                            knowCastellano.Bopedicto_texto_Esp__c = bopedicto.data_es_json.texto;
                        }
                        if(bopedicto.data_es_json.url_texto != null){
                            knowCastellano.Bopedicto_Url_texto_Esp__c = bopedicto.data_es_json.url_texto;
                        }
                        if(bopedicto.data_es_json.url_pdf != null){
                            knowCastellano.Bopedicto_Url_pdf_Esp__c = bopedicto.data_es_json.url_pdf;
                        }
                        if(bopedicto.data_es_json.url_html != null){
                            knowCastellano.Bopedicto_Url_html_Esp__c = bopedicto.data_es_json.url_html;
                        }
                        if(bopedicto.data_es_json.url_epub != null){
                            knowCastellano.Bopedicto_Url_epub_Esp__c = bopedicto.data_es_json.url_epub;
                        }
                        knowCastellano.ValidationStatus = 'Validated';
                        knowCastellano.RecordTypeId = bopedictoRecordTypeID;
                        knowCastellano.Language = 'es';
                        lstKnowledge.add(knowCastellano);
                    }else {
                        System.debug('No hay datos en data_es_json');
                    }
                    if(bopedicto.data_gl_json != null){
                        knowOtraLengua.Bopedicto_Id__c = String.valueOf(bopedicto.id);
                        knowOtraLengua.UrlName = String.valueOf(bopedicto.id)+'-'+'Gal';
                        knowOtraLengua.Bopedicto_Id_bop_edicto_externo__c = String.valueOf(bopedicto.id_bop_edicto_externo);
                        knowOtraLengua.Sumario__c = bopedicto.sumario;
                        knowOtraLengua.Activo__c = bopedicto.activo;
                        knowOtraLengua.Bopedicto_Bop_Id__c = String.valueOf(bopedicto.bop.Id); //Convert to String
                        knowOtraLengua.Bopedicto_bop_id_bop_externo__c = String.valueOf(bopedicto.bop.id_bop_externo); //Convert to String
                        knowOtraLengua.Ambitos__c = ambito;
                        knowOtraLengua.Entidades__c = entidad;
                        if(fecha_creacion != null){
                            knowOtraLengua.Fecha_de_creacion__c = fechaCreacion;
                        }
                        if(fecha_modificacion != null){
                            knowOtraLengua.fecha_modificacion__c = fechaModificacion;
                        }
                        if(bopedicto.data_gl_json.id_bop_edicto_externo != null){
                            knowOtraLengua.Bopedicto_Id_bop_edicto_externo_Gal__c = String.valueOf(bopedicto.data_gl_json.id_bop_edicto_externo);//Convert to String
                        }
                        if(bopedicto.data_gl_json.fecha_entrada != null){
                            fechaEntradaGalego = convertFechasJson(bopedicto.data_gl_json.fecha_entrada);
                            knowOtraLengua.Bopedicto_fecha_entrada_Gal__c = fechaEntradaGalego;
                        }
                        if(bopedicto.data_gl_json.numero_pagina != null){
                            knowOtraLengua.Bopedicto_numero_pagina_Gal__c = bopedicto.data_gl_json.numero_pagina;
                        }
                        if(bopedicto.data_gl_json.entidad_nombre != null){
                            knowOtraLengua.Bopedicto_entidad_nombre_Gal__c = bopedicto.data_gl_json.entidad_nombre;
                        }
                        if(bopedicto.data_gl_json.entidad_nif != null){
                            knowOtraLengua.Bopedicto_entidad_nif_Gal__c = bopedicto.data_gl_json.entidad_nif;
                        }
                        if(bopedicto.data_gl_json.sumario != null){
                            knowOtraLengua.Bopedicto_sumario_Gal__c = bopedicto.data_gl_json.sumario;
                            knowOtraLengua.Title = bopedicto.data_gl_json.sumario;
                            knowOtraLengua.Descripcion__c = bopedicto.data_es_json.sumario;
                        }else{
                            knowOtraLengua.Title = bopedicto.sumario;
                            knowOtraLengua.Descripcion__c = bopedicto.sumario;
                        }
                        if(bopedicto.data_gl_json.texto != null){
                            knowOtraLengua.Bopedicto_texto_Gal__c = bopedicto.data_gl_json.texto;
                        }
                        if(bopedicto.data_gl_json.url_texto != null){
                            knowOtraLengua.Bopedicto_Url_texto_Gal__c = bopedicto.data_gl_json.url_texto;
                        }
                        if(bopedicto.data_gl_json.url_pdf != null){
                            knowOtraLengua.Bopedicto_Url_pdf_Gal__c = bopedicto.data_gl_json.url_pdf;
                        }
                        if(bopedicto.data_gl_json.url_html != null){
                            knowOtraLengua.Bopedicto_Url_html_Gal__c = bopedicto.data_gl_json.url_html;
                        }
                        if(bopedicto.data_gl_json.url_epub != null){
                            knowOtraLengua.Bopedicto_Url_epub_Gal__c = bopedicto.data_gl_json.url_epub;
                        }
                        knowOtraLengua.ValidationStatus = 'Validated';
                        knowOtraLengua.RecordTypeId = bopedictoRecordTypeID;
                        knowOtraLengua.Language = 'es_MX';
                        lstKnowledge.add(knowOtraLengua);
                    }else{
                        System.debug('No hay datos en data_gl_json');
                    }
                    if(lstKnowledge.size()>0){
                        insert lstKnowledge ;
                        List<KnowledgeArticleVersion> lstKnowPublish = new List<KnowledgeArticleVersion>();
                        lstKnowPublish = [SELECT Id, KnowledgeArticleId, PublishStatus FROM KnowledgeArticleVersion WHERE PublishStatus = 'Draft'];
                        for(KnowledgeArticleVersion know : lstKnowPublish){
                            KbManagement.PublishingService.publishArticle(know.KnowledgeArticleId, true);
                        }
                    }
                }
            } catch (Exception ex) {
                System.debug('Ocurrió un error al procesar el bopedicto: ' + ex.getMessage());
            }
        }
    }
    private static Datetime convertFechasJson (String fecha) {
        Datetime fechaModificada = null;
        if(fecha != null){
            String fechaModificacionSinOffset = fecha.substring(0, 19);
            String offSetModificacion = fecha.substring(19, 22);
            Integer horasOffsetModificacion = Integer.valueOf(offSetModificacion);
            fechaModificacionSinOffset = fechaModificacionSinOffset.replace('T', ' ');
            fechaModificada = DateTime.valueOf(fechaModificacionSinOffset);
            fechaModificada = fechaModificada.addHours(horasOffsetModificacion);
        }
        return fechaModificada;
    }
}